package com.tagzxia3.tagzxia2.tagzxia1.te.src.main.java.com.talexs.talexessential.modules.realm.entity;

import com.talexs.talexessential.data.player.OnlinePlayerData;
import com.talexs.talexessential.modules.realm.PlayerRealm;
import com.talexs.talexessential.modules.realm.addon.IRealmAddon;
import com.talexs.talexessential.utils.item.ItemBuilder;
import io.papermc.paper.event.entity.EntityMoveEvent;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.Particle;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.block.Container;
import org.bukkit.block.sign.Side;
import org.bukkit.block.sign.SignSide;
import org.bukkit.configuration.MemoryConfiguration;
import org.bukkit.event.block.BlockExplodeEvent;
import org.bukkit.event.block.BlockFromToEvent;
import org.bukkit.event.entity.EntityDamageByEntityEvent;
import org.bukkit.event.entity.EntityExplodeEvent;
import org.bukkit.event.entity.EntitySpawnEvent;
import org.bukkit.event.player.PlayerInteractEvent;

import java.util.Objects;

/**
 * Define a realm flag that generated by flags.yml
 *
 * @author TalexDreamSoul
 * @since 1.0.0
 * 23/08/23 下午 10:54
 * Copyright (C) 2023-current TalexDreamSoul - All Rights Reserved
 */
@Getter
@Setter
@Accessors(chain = true)
@RequiredArgsConstructor
public abstract class RealmFlag implements IRealmAddon {

    private final String key;

    private ItemBuilder ib;

    private String status_enable_name, status_enable_desc;

    private String status_disable_name, status_disable_desc;

    private double cost;

    private int rank;

    private String rankMention, name;

    public static void quickAdapt(RealmFlag originFlag, MemoryConfiguration config) {
        String basePath = "Flags." + originFlag.key;

        originFlag.setCost(config.getDouble(basePath + ".cost"));
        originFlag.setRank(config.getInt(basePath + ".rank"));
        originFlag.setRankMention(config.getString(basePath + ".mention"));

        originFlag.setStatus_enable_name(config.getString(basePath + ".status.enable.name"));
        originFlag.setStatus_enable_desc(config.getString(basePath + ".status.enable.desc"));

        originFlag.setStatus_disable_name(config.getString(basePath + ".status.disable.name"));
        originFlag.setStatus_disable_desc(config.getString(basePath + ".status.disable.desc"));

        originFlag.setIb(new ItemBuilder(Material.valueOf(Objects.requireNonNull(config.getString(basePath + ".type")).toUpperCase()))
                .setName(originFlag.name = config.getString(basePath + ".name"))
                .setLore(config.getStringList(basePath + ".lore")));

    }

    @Override
    public void onEntityEnter(PlayerRealm pr, EntityMoveEvent event) {

    }

    @Override
    public void onEntityLeave(PlayerRealm pr, EntityMoveEvent event) {

    }

    @Override
    public void onBlockExploded(PlayerRealm pr, BlockExplodeEvent event, Block block) {

    }

    @Override
    public void onEntityExploded(PlayerRealm pr, EntityExplodeEvent event, Block block) {

    }

    @Override
    public void onPVP(OnlinePlayerData opd, PlayerRealm pr, EntityDamageByEntityEvent event) {

    }

    @Override
    public void onPVE(OnlinePlayerData opd, PlayerRealm pr, EntityDamageByEntityEvent event) {

    }

    @Override
    public void onMobSpawn(PlayerRealm pr, EntitySpawnEvent event) {

    }

    @Override
    public void onLiquidFlow(PlayerRealm pr, BlockFromToEvent event) {

    }

    @Override
    public void onInteract(OnlinePlayerData opd, PlayerRealm pr, PlayerInteractEvent event) {

    }

    @Override
    public boolean onTeleport(PlayerRealm pr, OnlinePlayerData opd) {
        return true;
    }

//    @Override
//    public boolean doVisible(PlayerRealm pr, OnlinePlayerData opd) {
//        return false;
//    }
    public void drawBarrierMarker(Location loc) {
        World world = loc.getWorld();

        world.spawnParticle(Particle.BLOCK_MARKER, loc.clone().add(0, .25, 0), 1, 0, 0, 0, 0, Material.BARRIER.createBlockData());
    }

    @Override
    public void onOpenSign(OnlinePlayerData opd, PlayerRealm pr, SignSide side, PlayerInteractEvent event) {

    }

    @Override
    public void onOpenContainer(OnlinePlayerData opd, PlayerRealm pr, Container container, PlayerInteractEvent event) {

    }
}
