name: TalexEssential
version: '${project.version}'
main: com.talexs.talexessential.TalexEssential
api-version: '1.20'
depend: [ProtocolLib, PlaceholderAPI, Vault, HeadDatabase]
authors: [TalexDreamSoul]
commands:
  te:
    aliases:
      - talexessential
      - talexess
      - ess
      - tl
      - talexs
  tea:
    aliases:
      - talexessentialadmin
      - talexessadmin
      - essadmin
      - tla
      - talexsa
  realm:
    aliases:
      - res
      - r
      - residence
      - ld
      - lingyu
      - ly
  randomteleports:
    aliases:
      - rt
      - rtp
      - randomtp
      - randomteleport