Settings:
  bail:
    rescue: /dp xxxx # 支持 papi
  dummy:
    triggers:
      # contains match
      npc:
        - 'DemoNpc' # match: DemoNpc1 HelloDemoNpc DemoNpc2 ...
      entity:
        # contains match - 满足则为警察势力
        police:
          - "[Police] " # match: [Police] Bar, [Police] Foo ...
  economy:
    rob: "500-1000" # or: 50% / 50%-60%