Souvenirs:
  DEBUG_COMMAND:
    type: LEVEL_UP
    head: 25846
    title: "&c测试人员"
    lore:
      - "在服务器中参与测试获得"
  ENDER_ANGEL:
    type: CONSUME
    head: 18149
    item: ENDERMAN_SPAWN_EGG
    title: "&e末影使者"
    lore:
      - "在服务器中获得 末影人刷怪蛋"
  VETERAN:
    type: GIVEN
    head: 59662
    title: "&2元老"
    lore:
      - "在 2023/08/01 日之前进入服务器获得"
  DEBUG:
    type: GIVEN
    head: 55742
    title: "&e维修人员"
    lore:
      - "在 2023/08/01 日凌晨服务器维修中获得"
