Settings:
  sells:
    - "COPPER_INGOT:1.6:ore"
    - "netherite_ingot:1288.88:ore"
    - "leather:1.9:material"
    - "ender_pearl:2.8:material"
    - "blaze_rod:1.5:material"
    - "redstone:1.8:ore"
    - "lapis_lazuli:1.9:ore"
    - "diamond:108.88:ore"
    - "amethyst_shard:16.88:ore"
    - "salmon:3.88:food"
    - "cod:2.2:food"
    - "tropical_fish:6.8:food"
    - "pufferfish:8.8:food"
    - "BONE_BLOCK:4.8:material"
    - "ROTTEN_FLESH:0.5:food"
    - "pumpkin:1.55:food"
    - "hay_block:2.5:food"
    - "melon:1.15:food"
    - "spider_eye:1.88:material"
    - "carrot:0.65:food"
    - "beetroot:0.28:food"
    - "pumpkin_pie:2.99:food"
    - "cake:18.88:food"
    - "cookie:0.35:food"
    - "potato:0.45:food"
    - "sweet_berries:0.15:food"
    - "rabbit:4.0:food"
    - "chicken:2.5:food"
    - "mutton:2.6:food"
    - "porkchop:2.0:food"
    - "beef:2.8:food"
    - "torch:0.15:material"
    - "dirt:0.5:build"
    - "cobblestone:0.04:build"
    - "sand:0.2:build"
    - "gravel:0.15:build"
    - "grass_block:0.6:build"
    - "oak_log:0.4:build"
    - "gunpowder:2.8:material"
    - "obsidian:5.88:build"
    - "quartz:0.32:build"
#    - "wither_skeleton_skull:500:material"
    - "glowstone:0.8:build"
    - "SUGAR_CANE:1.1:food"
    - "cactus:0.25:material"
    - "poppy:0.15:flower"
    - "NAUTILUS_SHELL:9.9:food"
  buys:
    - "netherite_ingot:1888.88:ore"
    - "redstone:11:ore"
    - "diamond:200:ore"
    - "oak_log:0.6:build"
    - "spruce_log:0.6:build"
    - "birch_log:0.6:build"
    - "jungle_log:0.6:build"
    - "acacia_log:0.6:build"
    - "dark_oak_log:0.6:build"
    - "mangrove_log:0.65:build"
    - "cherry_log:0.7:build"
    - "warped_stem:0.4:build"
    - "crimson_stem:0.4:build"
    - "stone:0.06:build"
    - "granite:0.08:build"
    - "diorite:0.08:build"
    - "andesite:0.08:build"
    - "bricks:0.8:build"
    - "quartz_block:1.25:build"
    - "purpur_block:1.05:build"
    - "prismarine:0.03:build"
    - "packed_mud:0.35:build"
    - "deepslate:0.06:build"
    - "sea_lantern:1.2:build"
    - "white_wool:0.4:build"
    - "terracotta:0.5:build"
    - "white_concrete:0.5:build"
    - "glass:0.99:build"
    - "copper_block:15:ore"
    - "oxidized_copper:18:ore"
    - "waxed_copper_block:20:ore"
    - "waxed_oxidized_copper:23:ore"
    - "leather:7.9:material"
    - "TOTEM_OF_UNDYING:2100:material"
    - "SAND:0.04:build"
    - "WHITE_DYE:0.5:material"
    - "LIGHT_GRAY_DYE:0.5:material"
    - "GRAY_DYE:0.5:material"
    - "BLACK_DYE:0.5:material"
    - "BROWN_DYE:0.5:material"
    - "RED_DYE:0.5:material"
    - "ORANGE_DYE:0.5:material"
    - "YELLOW_DYE:0.5:material"
    - "LIME_DYE:0.5:material"
    - "GREEN_DYE:0.5:material"
    - "LIGHT_BLUE_DYE:0.5:material"
    - "CYAN_DYE:0.5:material"
    - "BLUE_DYE:0.5:material"
    - "PURPLE_DYE:0.5:material"
    - "MAGENTA_DYE:0.5:material"
    - "PINK_DYE:0.5:material"
